export default {
    answer:[],//存储地址搜索结果
    history:[],//存储地址搜索历史纪录
    bol:false,//存储清空历史纪录标签是否显示的布尔值
    denglu:false,//存储是否登陆的布尔值
    wode:false,//存储页面显示的bol值
    sousuo:false,//存储页面显示的bol值
    dingdan:false,//存储页面显示的bol值
    wode:false,//存储页面显示的bol值
    city:"",//存储city页面的要显示的城市
    waimai_wz:{},//外面页面位置信息
    dianpu:'',//获取店铺对象
    dpbol:false,//店铺对象是否为空
    canpin:{},//餐品界面所需数据
    spshuju:[],//商品数据
    xiadan:[],//订单详情
    map:"",//搜索到的地址
    shdz:[],//收货位置数组
    spfl:{},//轮播图二级页面获取此数据
    ddliebiao:[],//订单列表数组
}